"""workflow_builder.py — maps an argus verdict dict → KeeperHub workflow spec.

Argus produces verdicts like:
  {
    "verdict": "CRITICAL",
    "vulnerability_class": "flash_loan_attack",
    "chain": "ethereum",
    "tx_hash": "0xabc...",
    "poc_block_number": 19234567,
    "contract_address": "0xdef...",
    "recommended_action": "pause position",
  }

This module converts that into a KeeperHub workflow (nodes + edges) that
executes the recommended action deterministically.
"""
from __future__ import annotations
from typing import Optional

# ── action registry ────────────────────────────────────────────────────────
# Maps vulnerability_class + recommended_action → workflow template.
# Each template is a list of (node_type, node_config) pairs.

def build_workflow(verdict: dict) -> dict:
    """Return a KeeperHub workflow spec for the given argus verdict.

    Returns:
        {
            "name": str,
            "description": str,
            "nodes": [...],
            "edges": [...],
            "inputs": {...},   # inputs to pass at execute time
        }
    """
    severity   = verdict.get("verdict", "MEDIUM")
    action     = verdict.get("recommended_action", "alert")
    chain      = verdict.get("chain", "ethereum")
    tx_hash    = verdict.get("tx_hash", "")
    contract   = verdict.get("contract_address", "")
    vuln_class = verdict.get("vulnerability_class", "unknown")
    summary    = verdict.get("summary", "Argus anomaly detected")

    name = f"argus-response-{vuln_class}-{severity.lower()}"
    description = (
        f"Auto-generated by Argus. Verdict: {severity}. "
        f"Class: {vuln_class}. Chain: {chain}. TX: {tx_hash}. "
        f"Action: {action}. Summary: {summary}"
    )

    # Choose node template based on action keyword
    action_lower = action.lower()

    if "pause" in action_lower or "circuit" in action_lower:
        nodes, edges = _pause_workflow(chain, contract)
    elif "move" in action_lower or "transfer" in action_lower:
        nodes, edges = _move_funds_workflow(chain, contract)
    elif "alert" in action_lower or "notify" in action_lower:
        nodes, edges = _alert_workflow(chain, tx_hash, summary)
    else:
        nodes, edges = _alert_workflow(chain, tx_hash, summary)

    return {
        "name":        name,
        "description": description,
        "nodes":       nodes,
        "edges":       edges,
        "inputs": {
            "chain":    chain,
            "tx_hash":  tx_hash,
            "contract": contract,
            "severity": severity,
            "summary":  summary,
        },
    }


def _pause_workflow(chain: str, contract: str) -> tuple[list, list]:
    """Workflow: call pause() on a contract."""
    nodes = [
        {
            "id":   "trigger",
            "type": "manual_trigger",
            "config": {"label": "Argus: pause contract"},
        },
        {
            "id":   "pause_call",
            "type": "contract_call",
            "config": {
                "chain":    chain,
                "address":  contract,
                "function": "pause()",
                "args":     [],
            },
        },
        {
            "id":   "receipt",
            "type": "emit_receipt",
            "config": {"label": "Argus audit receipt"},
        },
    ]
    edges = [
        {"from": "trigger",    "to": "pause_call"},
        {"from": "pause_call", "to": "receipt"},
    ]
    return nodes, edges


def _move_funds_workflow(chain: str, contract: str) -> tuple[list, list]:
    """Workflow: move funds to a safe address."""
    nodes = [
        {
            "id":   "trigger",
            "type": "manual_trigger",
            "config": {"label": "Argus: emergency fund move"},
        },
        {
            "id":   "transfer",
            "type": "token_transfer",
            "config": {
                "chain":      chain,
                "from":       contract,
                "to":         "{{safe_address}}",
                "amount":     "{{amount}}",
                "token":      "{{token_address}}",
            },
        },
        {
            "id":   "receipt",
            "type": "emit_receipt",
            "config": {"label": "Argus audit receipt"},
        },
    ]
    edges = [
        {"from": "trigger",  "to": "transfer"},
        {"from": "transfer", "to": "receipt"},
    ]
    return nodes, edges


def _alert_workflow(chain: str, tx_hash: str, summary: str) -> tuple[list, list]:
    """Workflow: emit an onchain alert event."""
    nodes = [
        {
            "id":   "trigger",
            "type": "manual_trigger",
            "config": {"label": "Argus: onchain alert"},
        },
        {
            "id":   "log_event",
            "type": "emit_event",
            "config": {
                "chain":   chain,
                "message": f"Argus alert: {summary} | tx: {tx_hash}",
            },
        },
        {
            "id":   "receipt",
            "type": "emit_receipt",
            "config": {"label": "Argus audit receipt"},
        },
    ]
    edges = [
        {"from": "trigger",   "to": "log_event"},
        {"from": "log_event", "to": "receipt"},
    ]
    return nodes, edges
